print("Complete Name: Jeff Justin G. Bonior")
print("Course : Bachelor of Science in Computer Science")
print("Section: CS1D")
print("Age:18")
print("Birthday: April 11, 2005")
print("Complete Home Address: Zone 4 Upper, Bulua, Cagayan de Oro")

print("Complete Name: Josephine Anne B. Aranas")
print("Course : Bachelor of Science in Computer Science")
print("Section: CS1D")
print("Age:20")
print("Birthday: April 16, 2003")
print("Complete Home Address: 124 San Juan 1 Lapasan, Cagayan de Oro City")

print("Complete Name: Aldwyn D. Betonio")
print("Course : Bachelor of Science in Computer Science")
print("Section: CS1D")
print("Age: 18")
print("Birthday: March 17, 2005")
print("Complete Home Address: Iponan, Cagayan de Oro City")